general {
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.local/share/wallpaper.jpg
    blur_passes = 3
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 60
    position = 0, -80
    halign = center
    valign = center

    inner_color = rgb(44475a)
    outer_color = rgb(bd93f9)
    outline_thickness = 2

    font_family = JetBrainsMono Nerd Font
    font_color = rgb(f8f8f2)

    placeholder_text = <i>Contrasena</i>
    check_color = rgb(50fa7b)
    fail_text = <i>$FAIL</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
