source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/hyprpaper.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/hypridle.conf
source = ~/.config/hypr/hyprlock.conf
source = ~/.config/hypr/hyprsunset.conf
source = ~/.config/hypr/xdph.conf

windowrule = suppress_event maximize, match:class .*
windowrule = tag +default-opacity, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

windowrulev2 = opacity 0.97 0.9, match:tag default-opacity
